// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_encode`, `with_chat`

/// Initialize the chat engine. Safe to call multiple times (no-op after first).
void chatInit({required String userName, required String dataDir}) => RustLib
    .instance
    .api
    .crateApiChatChatInit(userName: userName, dataDir: dataDir);

/// Returns true if the chat engine has been initialized.
bool chatIsInitialized() =>
    RustLib.instance.api.crateApiChatChatIsInitialized();

/// Create and return an intro bundle string for sharing out-of-band.
String chatGetIntro() => RustLib.instance.api.crateApiChatChatGetIntro();

/// Add a friend by providing their intro bundle; initiates the conversation.
void chatAddFriend({required String remoteUser, required String bundle}) =>
    RustLib.instance.api.crateApiChatChatAddFriend(
      remoteUser: remoteUser,
      bundle: bundle,
    );

/// List all chat sessions.
List<ChatInfo> chatListChats() =>
    RustLib.instance.api.crateApiChatChatListChats();

/// Switch the active chat to `remote_user`.
void chatSwitch({required String remoteUser}) =>
    RustLib.instance.api.crateApiChatChatSwitch(remoteUser: remoteUser);

/// Delete the chat with `remote_user`.
void chatDelete({required String remoteUser}) =>
    RustLib.instance.api.crateApiChatChatDelete(remoteUser: remoteUser);

/// Send a text message in the currently active chat.
void chatSend({required String content}) =>
    RustLib.instance.api.crateApiChatChatSend(content: content);

/// Poll for incoming envelopes. Returns names of users who sent new messages.
List<String> chatPoll() => RustLib.instance.api.crateApiChatChatPoll();

/// Get all messages for the active chat.
List<ChatMessage> chatGetMessages() =>
    RustLib.instance.api.crateApiChatChatGetMessages();

/// Returns the active chat's remote_user name, or empty string if none.
String chatGetActive() => RustLib.instance.api.crateApiChatChatGetActive();

/// Status info for display.
ChatStatusInfo chatGetStatus() =>
    RustLib.instance.api.crateApiChatChatGetStatus();

/// Peers currently visible via mDNS.
List<String> chatListPeers() =>
    RustLib.instance.api.crateApiChatChatListPeers();

class ChatInfo {
  final String remoteUser;
  final String chatId;
  final int messageCount;
  final bool isActive;

  const ChatInfo({
    required this.remoteUser,
    required this.chatId,
    required this.messageCount,
    required this.isActive,
  });

  @override
  int get hashCode =>
      remoteUser.hashCode ^
      chatId.hashCode ^
      messageCount.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatInfo &&
          runtimeType == other.runtimeType &&
          remoteUser == other.remoteUser &&
          chatId == other.chatId &&
          messageCount == other.messageCount &&
          isActive == other.isActive;
}

class ChatMessage {
  final bool fromSelf;
  final String content;
  final BigInt timestamp;

  const ChatMessage({
    required this.fromSelf,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode => fromSelf.hashCode ^ content.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          fromSelf == other.fromSelf &&
          content == other.content &&
          timestamp == other.timestamp;
}

class ChatStatusInfo {
  final String userName;
  final String addressHex;
  final int chatCount;
  final String activeChat;
  final int tcpPort;

  const ChatStatusInfo({
    required this.userName,
    required this.addressHex,
    required this.chatCount,
    required this.activeChat,
    required this.tcpPort,
  });

  @override
  int get hashCode =>
      userName.hashCode ^
      addressHex.hashCode ^
      chatCount.hashCode ^
      activeChat.hashCode ^
      tcpPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatStatusInfo &&
          runtimeType == other.runtimeType &&
          userName == other.userName &&
          addressHex == other.addressHex &&
          chatCount == other.chatCount &&
          activeChat == other.activeChat &&
          tcpPort == other.tcpPort;
}
