// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_local_ip_str`, `hex_encode`, `with_chat`

/// Initialize the chat engine. Safe to call multiple times (no-op after first).
void chatInit({required String userName, required String dataDir}) => RustLib
    .instance
    .api
    .crateApiChatChatInit(userName: userName, dataDir: dataDir);

/// Returns true if the chat engine has been initialized.
bool chatIsInitialized() =>
    RustLib.instance.api.crateApiChatChatIsInitialized();

/// Create and return an intro bundle string for sharing out-of-band.
String chatGetIntro() => RustLib.instance.api.crateApiChatChatGetIntro();

/// Add a friend by providing their intro bundle.
/// If the peer isn't reachable yet, the handshake is queued and retried automatically.
void chatAddFriend({required String remoteUser, required String bundle}) =>
    RustLib.instance.api.crateApiChatChatAddFriend(
      remoteUser: remoteUser,
      bundle: bundle,
    );

/// Manually register a peer's address when mDNS discovery doesn't work.
/// `addr` should be "ip:port", e.g. "192.168.1.101:54321".
void chatAddPeerAddr({required String name, required String addr}) =>
    RustLib.instance.api.crateApiChatChatAddPeerAddr(name: name, addr: addr);

/// List all chat sessions.
List<ChatInfo> chatListChats() =>
    RustLib.instance.api.crateApiChatChatListChats();

/// Switch the active chat to `remote_user`.
void chatSwitch({required String remoteUser}) =>
    RustLib.instance.api.crateApiChatChatSwitch(remoteUser: remoteUser);

/// Delete the chat with `remote_user`.
void chatDelete({required String remoteUser}) =>
    RustLib.instance.api.crateApiChatChatDelete(remoteUser: remoteUser);

/// Send a text message in the currently active chat.
void chatSend({required String content}) =>
    RustLib.instance.api.crateApiChatChatSend(content: content);

/// Poll: process incoming messages AND retry any pending sends.
/// Returns names of users who sent new messages.
List<String> chatPoll() => RustLib.instance.api.crateApiChatChatPoll();

/// Get all messages for the active chat.
List<ChatMessage> chatGetMessages() =>
    RustLib.instance.api.crateApiChatChatGetMessages();

/// Returns the active chat's remote_user name, or empty string if none.
String chatGetActive() => RustLib.instance.api.crateApiChatChatGetActive();

/// Status info including local IP and TCP port for manual peer setup.
ChatStatusInfo chatGetStatus() =>
    RustLib.instance.api.crateApiChatChatGetStatus();

/// Peers currently visible via mDNS, with their addresses.
List<String> chatListPeers() =>
    RustLib.instance.api.crateApiChatChatListPeers();

/// Peers with their IP:port addresses (useful for manual cross-reference).
List<PeerInfo> chatListPeersWithAddrs() =>
    RustLib.instance.api.crateApiChatChatListPeersWithAddrs();

/// Drop all in-memory state so a fresh `chat_init` can be called.
/// The caller is responsible for deleting the data files on disk.
void chatClear() => RustLib.instance.api.crateApiChatChatClear();

class ChatInfo {
  final String remoteUser;
  final String chatId;
  final int messageCount;
  final bool isActive;

  /// True if there are unsent handshake/message envelopes for this peer.
  final bool hasPending;

  const ChatInfo({
    required this.remoteUser,
    required this.chatId,
    required this.messageCount,
    required this.isActive,
    required this.hasPending,
  });

  @override
  int get hashCode =>
      remoteUser.hashCode ^
      chatId.hashCode ^
      messageCount.hashCode ^
      isActive.hashCode ^
      hasPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatInfo &&
          runtimeType == other.runtimeType &&
          remoteUser == other.remoteUser &&
          chatId == other.chatId &&
          messageCount == other.messageCount &&
          isActive == other.isActive &&
          hasPending == other.hasPending;
}

class ChatMessage {
  final bool fromSelf;
  final String content;
  final BigInt timestamp;

  const ChatMessage({
    required this.fromSelf,
    required this.content,
    required this.timestamp,
  });

  @override
  int get hashCode => fromSelf.hashCode ^ content.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          fromSelf == other.fromSelf &&
          content == other.content &&
          timestamp == other.timestamp;
}

class ChatStatusInfo {
  final String userName;
  final String addressHex;
  final int chatCount;
  final String activeChat;
  final int tcpPort;
  final String localIp;
  final int pendingCount;

  const ChatStatusInfo({
    required this.userName,
    required this.addressHex,
    required this.chatCount,
    required this.activeChat,
    required this.tcpPort,
    required this.localIp,
    required this.pendingCount,
  });

  @override
  int get hashCode =>
      userName.hashCode ^
      addressHex.hashCode ^
      chatCount.hashCode ^
      activeChat.hashCode ^
      tcpPort.hashCode ^
      localIp.hashCode ^
      pendingCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatStatusInfo &&
          runtimeType == other.runtimeType &&
          userName == other.userName &&
          addressHex == other.addressHex &&
          chatCount == other.chatCount &&
          activeChat == other.activeChat &&
          tcpPort == other.tcpPort &&
          localIp == other.localIp &&
          pendingCount == other.pendingCount;
}

class PeerInfo {
  final String name;
  final String addr;

  const PeerInfo({required this.name, required this.addr});

  @override
  int get hashCode => name.hashCode ^ addr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          addr == other.addr;
}
